testname: Pairwise Test
testId: pairwise_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: false
remoteService: service/write.php



pages:
    - type: generic
      id: first_page
      name: Instructions
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences. There are 6 songs to judge in this experiment. Reminder - In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.

    - type: mushra
      id: country
      name: Country Song
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences.
      enableLooping: true 
      reference: configs/resources/audio/originals/country.wav
      createAnchor35: false
      createAnchor70: false
      showWaveform: false
      stimuli:
          C1: configs/resources/audio/country/000/000.wav
          C2: configs/resources/audio/country/001/000.wav
          C3: configs/resources/audio/country/002/000.wav
          C4: configs/resources/audio/country/003/000.wav
          C5: configs/resources/audio/country/004/000.wav
      randomize: true

    - type: mushra
      id: disco
      name: Disco Song
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences.
      enableLooping: true 
      reference: configs/resources/audio/originals/disco.wav
      createAnchor35: false
      createAnchor70: false
      showWaveform: false
      stimuli:
          C1: configs/resources/audio/disco/000/000.wav
          C2: configs/resources/audio/disco/001/000.wav
          C3: configs/resources/audio/disco/002/000.wav
          C4: configs/resources/audio/disco/003/000.wav
          C5: configs/resources/audio/disco/004/000.wav
      randomize: true

    - type: mushra
      id: jazz
      name: Jazz Song
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences.
      enableLooping: true 
      reference: configs/resources/audio/originals/jazz.wav
      createAnchor35: false
      createAnchor70: false
      showWaveform: false
      stimuli:
          C1: configs/resources/audio/jazz/000/000.wav
          C2: configs/resources/audio/jazz/001/000.wav
          C3: configs/resources/audio/jazz/002/000.wav
          C4: configs/resources/audio/jazz/003/000.wav
          C5: configs/resources/audio/jazz/004/000.wav
      randomize: true

    - type: mushra
      id: pop
      name: Pop Song
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences.
      enableLooping: true 
      reference: configs/resources/audio/originals/pop.wav
      createAnchor35: false
      createAnchor70: false
      showWaveform: false
      stimuli:
          C1: configs/resources/audio/pop/000/000.wav
          C2: configs/resources/audio/pop/001/000.wav
          C3: configs/resources/audio/pop/002/000.wav
          C4: configs/resources/audio/pop/003/000.wav
          C5: configs/resources/audio/pop/004/000.wav
      randomize: true

    - type: mushra
      id: reggae
      name: Reggae Song
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences.
      enableLooping: true 
      reference: configs/resources/audio/originals/reggae.wav
      createAnchor35: false
      createAnchor70: false
      showWaveform: false
      stimuli:
          C1: configs/resources/audio/reggae/000/000.wav
          C2: configs/resources/audio/reggae/001/000.wav
          C3: configs/resources/audio/reggae/002/000.wav
          C4: configs/resources/audio/reggae/003/000.wav
          C5: configs/resources/audio/reggae/004/000.wav
      randomize: true

    - type: mushra
      id: rock
      name: Rock Song
      content: This is an experiment to learn about your preferences for how music is processed. You will be presented with a song segment that has been modified in different ways. In this experiment, you are deciding which version sounds the best to you. Try to make quick judgements, and avoid overthinking or analysing. You must give each a rating from 0 to 100 to indicate your preferences.
      enableLooping: true 
      reference: configs/resources/audio/originals/rock.wav
      createAnchor35: false
      createAnchor70: false
      showWaveform: false
      stimuli:
          C1: configs/resources/audio/rock/000/000.wav
          C2: configs/resources/audio/rock/001/000.wav
          C3: configs/resources/audio/rock/002/000.wav
          C4: configs/resources/audio/rock/003/000.wav
          C5: configs/resources/audio/rock/004/000.wav
      randomize: true



    - type: finish
      name: Thank you
      content: Thank you for completing this listening experiment!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 0
